### Default config
[yolo]
format = "onnx" # onnx or openvino or caffe
path = "/my/model/path/yolov7-tiny_640x640.onnx"
config_path = "/my/config/path.xml" # optional
transpose = false # set true for ultralythics-authored models
x = 640
y = 640
confidence_threshold = 0.995
nms_threshold = 0.05
person_class_index = 1 # usually 0 or 1 for most models
scale_factor = 255.0
threads = 4 # amount of models to run in parallel

[reid]
format = "onnx" # onnx or openvino or caffe
path = "/my/model/path/reid.onnx"
config_path = "/my/config/path.xml" # optional
output_layer_name = "reid_embedding"
score_threshold = 0.006
speed_threshold = 100
sma_window = 5
frames_to_follow = 3
time_to_live = 4

[kalman]
process_noise_cov = 0.01
measurement_noise_cov = 600

[backend]
device = "cpu" # cpu or vpu or gpu

[input]
type = "file" # file or webcam (WIP: stream)
path = "/my/video/path.mp4" # if type is "file"

[webserver]
port = 8080
read_timeout_sec = 120
write_timeout_sec = 120
shutdown_timeout_sec = 10

[logging]
level = "info"
stat_period_sec = 4 # 0 to disable the periodic stats

